import './globals.css'
import { Inter } from 'next/font/google'
import "@fontsource/montserrat"; 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Yash\'s template',
  description: 'Generated by Yash💘',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      
      <body style={{fontFamily:'montserrat'}} className={inter.className}>{children}</body>
    </html>
  )
}
